name: create-resolve-app testing

on:
  push:
    branches:
      - feature/cra-test-workflow

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Yarn Cache Clean
        run: yarn cache clean

      - name: Install
        run: |
          yarn install --frozen-lockfile
          yarn build-packages
          yarn add pm2 -W
          pm2 delete local-registry || true
          pm2 start packages/internal/local-registry/bin/index.js --name local-registry

      - name: Tutorial E2E test
        run: yarn tutorial-test:e2e

      - name: Examples E2E test
        run: yarn test:cra -c ${{ github.sha }} --local-registry
