name: create-resolve-app testing

on:
  push:
    branches:
      - feature/cra-test-workflow

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Yarn Cache Clean
        run: yarn cache clean

      - name: Install
        run: |
          yarn install --frozen-lockfile
          yarn build-packages
          npm install pm2 -g
          pm2 delete local-registry || true
          pm2 start packages/internal/local-registry/bin/index.js --name local-registry

      - name: Tutorial E2E test
        env:
          RESOLVE_E2E_TESTS_BROWSER: chrome
          RESOLVE_E2E_TESTS_HEADLESS_MODE: true
        run: yarn tutorial-test:e2e

      - name: Examples E2E test
        env:
          RESOLVE_E2E_TESTS_BROWSER: chrome
          RESOLVE_E2E_TESTS_HEADLESS_MODE: true
        run: yarn test:cra -c ${{ github.sha }} --local-registry
